### PR TITLE
fa: remove unmaintained source code of Forester from this repository

### PR DESCRIPTION
**Pull request by kdudka**
Development of Forester was moved elsewhere long time ago.  See the project page for details:
http://www.fit.vutbr.cz/research/groups/verifit/tools/forester/

### CODE REVIEW

**Comment by kdudka** [comment]
@versokova Any objections to this cleanup?

**Comment by versokova** [comment]
Not at all. Probably a question for @ondrik.

**Comment by ondrik** [comment]
fine for me

**Comment by kdudka** [comment]
Thank you both for review!  Merging...

**Pull request merged**
