### PR TITLE
cl/cl_dotgen.cc: fix for generating invisible *dot files

### PR DESCRIPTION
**Pull request by versokova**
When you call predator `-gen-dot` with `../file.c`, you "lose" the generated files. A better solution would be to use only a filename, but this works too.

### CODE REVIEW

**Comment by kdudka** [comment]
Nice catch.  This bug was introduced in commit f74a6f69cd5449456116c415e61cd35f2d791e26.  Creating hidden `.dot` files for non-hidden `.c` files was definitely not intended.  But I am not sure if the proposed change makes the behavior more intuitive.  What if we limited the problematic substitution for absolute paths only?

```diff
--- a/cl/cl_dotgen.cc
+++ b/cl/cl_dotgen.cc
@@ -215,8 +215,10 @@ const char *ClDotGenerator::EtColors[ClDotGenerator::CNT_ET] = {
 void ClDotGenerator::createDotFile(std::ofstream &str, std::string fileName,
                                    bool appendSuffix)
 {
-    // do not create dot files in /usr/include and the like
-    boost::algorithm::replace_all(fileName, "/", "-");
+    CL_BREAK_IF(fileName.empty());
+    if (fileName[0] == '/')
+        // do not create dot files in /usr/include and the like
+        boost::algorithm::replace_all(fileName, "/", "-");

     if (appendSuffix)
         fileName += ".dot";
```

**Comment by versokova** [comment]
This change creates `../file.c.dot`, `../file.c-func.dot`... which is in different directory than where the predator is called. For me it is less intuitive, even more if you set `-gen-dot=dotfile.dot` (still create `../file.c-func.dot`). I would expect something with the prefix `dotfile.dot` like `dotfile.dot-func.dot`.
```
484    const struct cl_cst &cst = fnc->data.cst;
485    loc_ = cst.data.cst_fnc.loc;
486    fnc_ = cst.data.cst_fnc.name;
487
488    ClDotGenerator::createDotFile(perFncOut_,
489                                  string(loc_.file) + "-" + fnc_,
490                                  true);
```
What if we use `glDotFile` insted of `loc_.file`? And if `glDotFile` is not set and file is a relative path, then the output dotfile should be relative path. What do you think? should i change it like that?

**Comment by kdudka** [comment]
Good point.  `gcc -c ../file.c` also creates `file.o` in the current working directory (CWD) rather than `../file.o`.  Creating all `.dot` files in CWD makes sense to me.  We just need to make sure that there are now collisions on them.

**Comment by kdudka** [comment]
And yes, if `glDotFile` is specified, all the other files should probably be in the same directory as `glDotFile`.

**Comment by kdudka** [comment]
The last change broke a test-case where we write graphs to `/dev/null`, which is not really practical I must admit: https://github.com/kdudka/predator/blob/f5d281c4d8703972721568cea65a19a7b8985eff/cl/tests/CMakeLists.txt#L73

I guess we can just modify the test to generate the graph in the build directory instead.

**Comment by kdudka** [comment]
Thanks for the update!  Pushing now with i minor coding style tweak on top of it.

**Pull request closed without merging**
