### PR TITLE
sl: report memory leak if return value of *alloc() is not used

### PR DESCRIPTION
**Pull request by kdudka**
... rather than reporting prototype error, which is misleading.

### CODE REVIEW

**Comment by kdudka** [comment]
@versokova I am proposing a tiny follow-up to #22. Could you please have a look?

**Comment by versokova** [comment]
It seems good. Thanks for fixs.

For clang is output  `warning: memory leak detected while destroying a variable on stack` because it gives result of return-function to the register which is never used. I add it to the `llvm.patch` later.

**Comment by kdudka** [comment]
Thanks for review!  Merging...

> For clang is output warning: memory leak detected while destroying a variable on stack

I think this is fine as long as the location info is correct.

**Comment by kdudka** [comment]
It is still not perfect.  I have opened pull request #24 to improve it.

**Pull request closed without merging**
