### PR TITLE
Partially replace Boost with C++11

### PR DESCRIPTION
**Pull request by lzaoral**
* replace `BOOST_FOREACH` with range-based for loops
* replace `BOOST_STATIC_ASSERT` with `static_assert`
* replace `boost/tuple/tuple.hpp` with `tuple` from standard library

### CODE REVIEW

**Comment by kdudka** [comment]
These changes (especially the `BOOST_FOREACH` one) are going to trigger excessive conflicts in all forks and downstream patches of Predator.  I think we should discuss the changes with downstream consumers first.

**Comment by kdudka** [comment]
@versokova Do you still maintain any downstream changes of Predator that could possibly conflict with this pull request?

**Comment by versokova** [comment]
Only https://github.com/versokova/predator/tree/json, no conflicts with this PR.

**Comment by kdudka** [comment]
@versokova Sounds good.  Thanks for confirmation!

@lzaoral I guess you coordinated this somehow with the people behind https://github.com/staticafi/predator , did you?

**Comment by lzaoral** [comment]
@kdudka The [statica](https://github.com/staticafi/predator) fork contains 22 extra commits (with 2 being also reverted) and the `BOOST_FOREACH` macro is used only at two places in them. So the subsequent rebase would be trivial.

**Review by kdudka — APPROVED** [review]
Sounds like it should be safe to merge this.  Please put the following line to the commit message of the `BOOST_FOREACH` commit (mainly to keep evidence that we tried to assess the impact before merging this change):
```
Closes: https://github.com/kdudka/predator/pull/82
```
Thanks!

**Comment by lzaoral** [comment]
Thanks @kdudka, done! I'll merge once the CI finishes. Btw, all projects in the `csutils` namespace will need a commit similar to 241ccd4 for working Packit, though without the `gcc` dependency.

**Pull request merged**
